// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/circle-from-3-points.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var vec3 = z.array(z.number()).length(3).describe("[X, Y, Z] coordinates");
var sub = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
var add = (a, b) => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
var scale = (a, s) => [a[0] * s, a[1] * s, a[2] * s];
var dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
var cross = (a, b) => [
  a[1] * b[2] - a[2] * b[1],
  a[2] * b[0] - a[0] * b[2],
  a[0] * b[1] - a[1] * b[0]
];
var norm = (a) => Math.sqrt(dot(a, a));
var unit = (a) => {
  const n = norm(a);
  return n < 1e-12 ? [0, 0, 0] : [a[0] / n, a[1] / n, a[2] / n];
};
var circle_from_3_points_default = defineTool({
  name: "circle_from_3_points",
  title: "Circle from 3 points",
  description: "Compute the circle (center, radius, unit normal) that passes through three 3D points. Returns null-like error if the points are collinear.",
  inputSchema: {
    p1: vec3,
    p2: vec3,
    p3: vec3
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ p1, p2, p3 }) => {
    const P1 = p1, P2 = p2, P3 = p3;
    const v1 = sub(P2, P1);
    const v2 = sub(P3, P1);
    const n = cross(v1, v2);
    if (norm(n) < 1e-10) {
      return {
        content: [{ type: "text", text: "Points are collinear; circle is undefined." }],
        isError: true
      };
    }
    const nrm = unit(n);
    const v1sq = dot(v1, v1);
    const v2sq = dot(v2, v2);
    const denom = 2 * dot(n, n);
    const alpha = v2sq * dot(v1, sub(v1, v2)) / denom;
    const beta = v1sq * dot(v2, sub(v2, v1)) / denom;
    const center = add(P1, add(scale(v1, alpha), scale(v2, beta)));
    const radius = norm(sub(P1, center));
    const result = { center, radius, normal: nrm };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/circle-from-center.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var vec32 = z2.array(z2.number()).length(3).describe("[X, Y, Z] coordinates");
var sub2 = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
var dot2 = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
var cross2 = (a, b) => [
  a[1] * b[2] - a[2] * b[1],
  a[2] * b[0] - a[0] * b[2],
  a[0] * b[1] - a[1] * b[0]
];
var norm2 = (a) => Math.sqrt(dot2(a, a));
var unit2 = (a) => {
  const n = norm2(a);
  return n < 1e-12 ? [0, 0, 0] : [a[0] / n, a[1] / n, a[2] / n];
};
var circle_from_center_default = defineTool2({
  name: "circle_from_center_and_2_points",
  title: "Circle from center + 2 rim points",
  description: "Compute the circle (center, radius = mean of the two distances, unit normal) from a center point and two points on the rim.",
  inputSchema: {
    center: vec32,
    r1: vec32,
    r2: vec32
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ center, r1, r2 }) => {
    const C = center, R1 = r1, R2 = r2;
    const v1 = sub2(R1, C);
    const v2 = sub2(R2, C);
    const n = cross2(v1, v2);
    if (norm2(n) < 1e-10) {
      return {
        content: [{ type: "text", text: "Rim vectors are collinear; normal is undefined." }],
        isError: true
      };
    }
    const result = { center: C, radius: (norm2(v1) + norm2(v2)) / 2, normal: unit2(n) };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/generate-sections.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var vec33 = z3.array(z3.number()).length(3).describe("[X, Y, Z]");
var sub3 = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
var add2 = (a, b) => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
var scale2 = (a, s) => [a[0] * s, a[1] * s, a[2] * s];
var dot3 = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
var norm3 = (a) => Math.sqrt(dot3(a, a));
var unit3 = (a) => {
  const n = norm3(a);
  return n < 1e-12 ? [0, 0, 0] : [a[0] / n, a[1] / n, a[2] / n];
};
var PLANE_TPL = `LIBRARY:
  PLANE: {name}
    Apply Instancing Transform = On
    Bound Radius = {bound} [{unit}]
    Domain List = {domain}
    Option = Point and Normal
    Plane Bounds = Circular
    Plane Type = Slice
    Point = {cx} [{unit}], {cy} [{unit}], {cz} [{unit}]
    Normal = {nx}, {ny}, {nz}
  END
END`;
var generate_sections_default = defineTool3({
  name: "generate_sections",
  title: "Generate circular sections along a direction",
  description: "Given a base circle center C1 and a target circle center C2, generate N circular sections stepping from C1 toward C2 (or by fixed step). Returns CFX-Post PLANE blocks, a CSV table, and a JSON array.",
  inputSchema: {
    c1: vec33.describe("Base circle center"),
    c2: vec33.describe("Target circle center (defines direction)"),
    normal: vec33.describe("Unit normal of the base circle"),
    radius: z3.number().positive().describe("Radius applied to every generated section"),
    count: z3.number().int().min(1).max(500).describe("Number of sections to generate"),
    include_first: z3.boolean().default(true).describe("Include the base circle (C1) as the first section"),
    dist_mode: z3.enum(["step", "total"]).default("total").describe("'total' = spread N points from C1 to C2; 'step' = each section separated by `step` along the C1\u2192C2 direction"),
    step: z3.number().default(0).describe("Step distance in units (used when dist_mode='step')"),
    prefix: z3.string().default("SEC").describe("Section name prefix"),
    domain: z3.string().default("Nozzle").describe("CFX domain name"),
    unit: z3.string().default("mm").describe("CFX unit label, e.g. mm or m"),
    bound: z3.number().default(50).describe("CFX Plane Bound Radius (in `unit`)"),
    decimals: z3.number().int().min(0).max(10).default(6)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args) => {
    const C1 = args.c1;
    const C2 = args.c2;
    const N = args.normal;
    const dir = sub3(C2, C1);
    const dist = norm3(dir);
    if (dist < 1e-10) {
      return { content: [{ type: "text", text: "C1 and C2 are identical; direction undefined." }], isError: true };
    }
    const u = unit3(dir);
    const startIdx = args.include_first ? 0 : 1;
    const centers = [];
    if (args.dist_mode === "total") {
      const denom = args.include_first ? Math.max(args.count - 1, 1) : args.count;
      for (let i = startIdx; i < (args.include_first ? args.count : args.count + 1); i++) {
        const t = i / denom;
        centers.push(add2(C1, scale2(u, t * dist)));
        if (centers.length >= args.count) break;
      }
    } else {
      for (let i = 0; i < args.count + (args.include_first ? 0 : 1); i++) {
        if (!args.include_first && i === 0) continue;
        centers.push(add2(C1, scale2(u, i * args.step)));
        if (centers.length >= args.count) break;
      }
    }
    const d = args.decimals;
    const f = (n) => n.toFixed(d);
    const sections = centers.map((c, i) => ({
      name: `${args.prefix}_${String(i + 1).padStart(2, "0")}`,
      center: c,
      normal: N,
      radius: args.radius
    }));
    const plane = sections.map(
      (s) => PLANE_TPL.replace(/\{(name|domain|unit|bound|cx|cy|cz|nx|ny|nz|r)\}/g, (_, k) => {
        const map = {
          name: s.name,
          domain: args.domain,
          unit: args.unit,
          bound: String(args.bound),
          cx: f(s.center[0]),
          cy: f(s.center[1]),
          cz: f(s.center[2]),
          nx: f(s.normal[0]),
          ny: f(s.normal[1]),
          nz: f(s.normal[2]),
          r: f(s.radius)
        };
        return map[k] ?? "";
      })
    ).join("\n\n");
    const csv = "name,cx,cy,cz,nx,ny,nz,radius\n" + sections.map((s) => [s.name, ...s.center, ...s.normal, s.radius].map((v) => typeof v === "number" ? f(v) : v).join(",")).join("\n");
    const summary = `Generated ${sections.length} section(s) along [${f(u[0])}, ${f(u[1])}, ${f(u[2])}] over ${f(dist)} ${args.unit}.`;
    return {
      content: [
        { type: "text", text: summary },
        { type: "text", text: "PLANE:\n" + plane },
        { type: "text", text: "CSV:\n" + csv }
      ],
      structuredContent: { count: sections.length, sections, plane, csv }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cfx-circle-section-mcp",
  title: "CST / CFX-Post Circle Section Generator",
  version: "0.1.0",
  instructions: "Compute 3D circle geometry (center, radius, unit normal) from 3 points or from a center + 2 rim points, and batch-generate circular cross sections along a direction. Outputs CFX-Post PLANE blocks, CSV, and JSON so an assistant can prepare CFD post-processing inputs.",
  tools: [circle_from_3_points_default, circle_from_center_default, generate_sections_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
